apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-reindex" (include "thoth.fullname" .) }}
  labels:
    app.kubernetes.io/component: reindex
    {{- include "thoth.labels" . | nindent 4 }}
spec:
  schedule: "30 6 * * *"
  timeZone: Europe/London
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: reindex
            {{- include "thoth.labels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          initContainers:
            {{- include "thoth.initContainers" . | nindent 12 }}
          containers:
            - name: reindex
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: ["reindex"]
              envFrom:
                {{- include "thoth.envFrom" . | nindent 16 }}
              volumeMounts:
                {{- include "thoth.volumeMounts" . | nindent 16 }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            {{- include "thoth.volumes" . | nindent 12 }}
