apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thoth.vaultPvcName" . }}
  labels:
    {{- include "thoth.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.vault.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.vault.size | quote }}
  {{- if .Values.storage.vault.storageClassName }}
  storageClassName: {{ .Values.storage.vault.storageClassName | quote }}
  {{- end }}
