apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thoth.thothHomePvcName" . }}
  labels:
    {{- include "thoth.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.thothHome.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.thothHome.size | quote }}
  {{- if .Values.storage.thothHome.storageClassName }}
  storageClassName: {{ .Values.storage.thothHome.storageClassName | quote }}
  {{- end }}
